name = "x-login"
main = "main.ts"
compatibility_date = "2025-01-25"

routes = [
  { pattern = "xlogin.uithub.com", custom_domain = true },
  { pattern = "x.smootherauth.com", custom_domain = true }
]
